CREATE TABLE IF NOT EXISTS gastos (
  id SERIAL PRIMARY KEY,
  descricao VARCHAR(255) NOT NULL,
  valor NUMERIC(10, 2) NOT NULL,
  categoria VARCHAR(100),
  data DATE NOT NULL DEFAULT CURRENT_DATE,
  criado_em TIMESTAMP NOT NULL DEFAULT NOW()
);
